
merge-key: "mas/drroc4/drgitopsapp"

ibm_mas_masapp_configs:
  - mas_app_id: manage
    mas_app_namespace: mas-drgitopsapp-manage
    mas_app_ws_apiversion: apps.mas.ibm.com/v1
    mas_app_ws_kind: ManageWorkspace
    mas_workspace_id: drgitopswks

    mas_manual_cert_mgmt: false
    run_sanity_test: false

    mas_appws_spec:
      bindings:
        jdbc: system
      components:
        base:
          version: latest
        utilities:
          version: latest
        spatial:
          version: latest
      settings:
        db:
          dbSchema: maximo
          tableSpace: MAX_DATA
          indexSpace: MAX_INDEX
        deployment:
          autoGenerateEncryptionKeys: false
          defaultJMS: false
        languages:
          default: EN
        serverTimezone: America/Chicago
        customizationList: []
        persistentVolumes:
          - pvcName: jmsstore
            mountPath: /jmsstore
            size: 20Gi
            storageClassName: isilon
            accessModes:
              - ReadWriteMany
          - pvcName: globaldir
            mountPath: /globaldir
            size: 20Gi
            storageClassName: isilon
            accessModes:
              - ReadWriteMany
        serverBundles:
          - name: ui
            bundleType: ui
            isDefault: true
            replica: 1
            routeSubDomain: ui
          - name: cron
            bundleType: cron
            isDefault: false
            replica: 1
            routeSubDomain: cron
          - name: mea
            bundleType: mea
            isDefault: false
            replica: 1
            routeSubDomain: mea
          - name: jms
            bundleType: standalonejms
            isDefault: false
            replica: 1
            routeSubDomain: jms

    storage_class_definitions: {}
